### ISSUE TITLE
Ενιαίο αποθετήριο στο https://github.com/grnet/team-collaboration-toolkit

### ISSUE THREAD

**Issue by tgkarounos** [grnet/team-collaboration-toolkit#2]
@aptiko Στο https://github.com/grnet/team-collaboration-toolkit να εντάξουμε ως "sub-directories", τα nextcloud, matrix, jttsi, moodle & BigBluButton.

**Comment by aptiko** [comment]
Κλείνω αυτό το δελτίο γιατί κάποια πράγματα έχουν γίνει και κάποια θα πρέπει να γίνουν χωριστά. Τα nextcloud και jitsi ήδη έχουν μπει στο repository. Το matrix δεν έχει μπει γιατί γι' αυτό χρησιμοποιούμε ένα third-party, και η πληροφορία αυτή είναι τεκμηριωμένη κατάλληλα. Το BigBlueButton είναι σε άλλο repository που θα ξεκινήσω να review και αν το κρίνουμε κατάλληλο θα το εντάξουμε. Για το moodle δεν έχω ξανακούσει και αν χρειαστεί θα το βάλουμε στην ουρά.
