### ISSUE TITLE
Στατιστικά χρήσης 

### ISSUE THREAD

**Issue by tgkarounos** [grnet/team-collaboration-toolkit#3]
@gpapadoka Να βγάζουμε στατιστικά χρήσης των υποδομών και των nextcloud, Matrix & Jitsi.

**Comment by aptiko** [comment]
Κλείνω αυτό το δελτίο γιατί είναι υπερβολικά ευρύ. Έχω στην προσωπική μου ουρά κάποια στατιστικά για το Jitsi, και βρισκόμαστε σε διαδικασία να δούμε γενικότερα τι στατιστικά χρειαζόμαστε και γιατί.
