### ISSUE TITLE
Επικαιροποίηση εισαγωγικού κειμένου https://github.com/grnet/team-collaboration-toolkit

### ISSUE THREAD

**Issue by tgkarounos** [grnet/team-collaboration-toolkit#4]
@toons01 @aptiko @gpapadoka @MedeaGRNET @tbousiou Να αναδιοργανωθεί το readme ώστε να απευθύνεται σε στελέχη του δημοσίου που θέλουν εισηγηθούν στις υπηρεσίες τους τη χρήση των [nextcloud](https://nextcloud.com/), [matrix](https://matrix.org/), [jitsi](https://meet.jit.si/), [moodle](https://moodle.org/) & [BigBlueButton](https://bigbluebutton.org/).

Μπορούμε να αξιοποιήσουμε και το [GitHub Pages](https://pages.github.com/),

**Comment by tbousiou** [comment]
Με το Github page μπορούμε να φτιάξουμε κάτι σαν site, εναλλακτικά για κάτι πιο απλό σε στυλ documentation μπορούμε και με το Wiki που έχει κάθε αποθετήριο.
